export const colors = [
  "#000000",
  "#ffffff",
  "#733C3C",
  "#8479E1",
  "#B4ECE3",
  "#FFF8D5",
  "#FD5D5D",
  "#FF8080",
  "#FFF7BC",
  "#C0EDA6",
  "#FAD9E6",
  "#E4AEC5",
  "#5F7464",
  "#243D25",
  "#FF6B6B",
  "#FFD93D",
  "#6BCB77",
  "#4D96FF",
  "#1C0C5B",
  "#C84B31",
  "#700B97",
  "#A12568",
  "#346751",
  "#31112C",
  "#1A1A2E",
  "#1F4068",
  "#C70D3A",
  "#AF0404",
  "#83142C",
  "#3E432E",
  "#DBEDF3",
  "#FF8BA0",
  "#14FFEC",
  "#0E1555",
  "#E9B5D2",
];

export const fonts = [
  { fontfamily: "Noto Sans", fontname: "Noto Sans", className: "" },
  { fontfamily: "Nanum Gothic", fontname: "나눔 고딕", className: "" },
  { fontfamily: "Nanum Myeongjo", fontname: "나눔 명조", className: "" },
  { fontfamily: "Nanum Pen", fontname: "나눔 펜", className: "" },
  { fontfamily: "Nanum Brush", fontname: "나눔 브러쉬", className: "" },
  { fontfamily: "Gowun Dodum", fontname: "고운 돋움", className: "" },
  { fontfamily: "Gowun Batang", fontname: "고운 바탕", className: "" },
  { fontfamily: "Jua", fontname: "주아", className: "" },
  { fontfamily: "Sunflower", fontname: "Sunflower", className: "" },
  { fontfamily: "Dokdo", fontname: "독도", className: "" },
  { fontfamily: "Gaegu Light", fontname: "개구 라이트", className: "" },
  { fontfamily: "Gaegu", fontname: "개구", className: "" },
  { fontfamily: "Cute", fontname: "큐트", className: "" },
  { fontfamily: "Dongle", fontname: "동글", className: "" },
  { fontfamily: "Single Day", fontname: "싱글 데이", className: "" },
  { fontfamily: "Yeon Sung", fontname: "연성", className: "" },
  { fontfamily: "Hamlet", fontname: "햄릿", className: "" },
];

export const DEFAULT_SEO = {
  title: "CU;LETTER, 큐레터",
  description: "큐레터; 커스텀 편지 작성, 전송을 쉽게 해보세요!",
  canonical: "https://www.culetter.site/",
  openGraph: {
    type: "website",
    locale: "ko_KR",
    url: "/img/Mailbox.png",
    title: "큐레터",
    site_name: "CU;LETTER",
    images: [
      {
        url: "/img/Mailbox.png",
        width: 600,
        height: 315,
        alt: "큐레터 로고",
      },
    ],
  },
};
